"""
SQLAlchemy ORM models for the Industrial Safety Monitoring System.
"""

from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class SeverityLevel(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, enum.Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class SensorType(str, enum.Enum):
    TEMPERATURE = "TEMPERATURE"
    PRESSURE = "PRESSURE"
    GAS = "GAS"
    SMOKE = "SMOKE"
    VIBRATION = "VIBRATION"
    HUMIDITY = "HUMIDITY"
    MOTION = "MOTION"


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    username: Mapped[str] = mapped_column(String(50), unique=True, nullable=False, index=True)
    email: Mapped[str] = mapped_column(String(120), unique=True, nullable=False, index=True)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    full_name: Mapped[str | None] = mapped_column(String(120))
    phone_number: Mapped[str | None] = mapped_column(String(20))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    is_admin: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now()
    )

    alerts: Mapped[list["Alert"]] = relationship("Alert", back_populates="acknowledged_by_user")


class Zone(Base):
    """Physical zone / area being monitored."""

    __tablename__ = "zones"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    location: Mapped[str | None] = mapped_column(String(200))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    sensors: Mapped[list["Sensor"]] = relationship("Sensor", back_populates="zone")
    alerts: Mapped[list["Alert"]] = relationship("Alert", back_populates="zone")


class Sensor(Base):
    """IoT sensor device."""

    __tablename__ = "sensors"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    sensor_type: Mapped[SensorType] = mapped_column(Enum(SensorType), nullable=False)
    unit: Mapped[str | None] = mapped_column(String(20))
    min_threshold: Mapped[float | None] = mapped_column(Float)
    max_threshold: Mapped[float | None] = mapped_column(Float)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    zone_id: Mapped[int] = mapped_column(ForeignKey("zones.id"))
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    zone: Mapped["Zone"] = relationship("Zone", back_populates="sensors")
    readings: Mapped[list["SensorReading"]] = relationship("SensorReading", back_populates="sensor")
    alerts: Mapped[list["Alert"]] = relationship("Alert", back_populates="sensor")


class SensorReading(Base):
    """Time-series sensor data point."""

    __tablename__ = "sensor_readings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    sensor_id: Mapped[int] = mapped_column(ForeignKey("sensors.id"), index=True)
    value: Mapped[float] = mapped_column(Float, nullable=False)
    is_anomaly: Mapped[bool] = mapped_column(Boolean, default=False)
    anomaly_score: Mapped[float | None] = mapped_column(Float)
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), index=True
    )

    sensor: Mapped["Sensor"] = relationship("Sensor", back_populates="readings")


class Alert(Base):
    """Safety alert generated by anomaly detection or threshold breach."""

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[SeverityLevel] = mapped_column(
        Enum(SeverityLevel), default=SeverityLevel.MEDIUM
    )
    status: Mapped[AlertStatus] = mapped_column(
        Enum(AlertStatus), default=AlertStatus.PENDING
    )
    sms_sent: Mapped[bool] = mapped_column(Boolean, default=False)
    sms_sid: Mapped[str | None] = mapped_column(String(100))

    sensor_id: Mapped[int | None] = mapped_column(ForeignKey("sensors.id"))
    zone_id: Mapped[int | None] = mapped_column(ForeignKey("zones.id"))
    acknowledged_by: Mapped[int | None] = mapped_column(ForeignKey("users.id"))

    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), index=True)
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime)

    sensor: Mapped["Sensor | None"] = relationship("Sensor", back_populates="alerts")
    zone: Mapped["Zone | None"] = relationship("Zone", back_populates="alerts")
    acknowledged_by_user: Mapped["User | None"] = relationship("User", back_populates="alerts")


class SMSLog(Base):
    """Log of all SMS messages sent via Twilio."""

    __tablename__ = "sms_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    to_number: Mapped[str] = mapped_column(String(20), nullable=False)
    from_number: Mapped[str] = mapped_column(String(20), nullable=False)
    message_body: Mapped[str] = mapped_column(Text, nullable=False)
    twilio_sid: Mapped[str | None] = mapped_column(String(100), unique=True)
    status: Mapped[str] = mapped_column(String(30), default="queued")
    error_message: Mapped[str | None] = mapped_column(Text)
    sent_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
