"""
Automated Setup Script for BE Project Final
==========================================
Run this ONCE after cloning the repo:

    python setup.py

What it does automatically:
  Step 2 — Creates a Python virtual environment
  Step 3 — Installs all dependencies from requirements.txt
  Step 4 — Copies .env.example → .env  (prompts for your values)
  Step 5 — Creates the MySQL database
  Step 6 — Creates all tables (no alembic needed)

After this script finishes, just run:
    python run.py
"""

import os
import sys
import subprocess
import shutil
import platform
import getpass


# ── colour helpers ──────────────────────────────────────────────────────────
def green(t):  return f"\033[92m{t}\033[0m"
def yellow(t): return f"\033[93m{t}\033[0m"
def red(t):    return f"\033[91m{t}\033[0m"
def bold(t):   return f"\033[1m{t}\033[0m"


def step(n, title):
    print(f"\n{bold(f'[Step {n}/5]')} {title}")
    print("─" * 50)


def run(cmd, cwd=None, capture=False):
    """Run a shell command, exit on failure."""
    result = subprocess.run(
        cmd, shell=True, cwd=cwd,
        capture_output=capture, text=True
    )
    if result.returncode != 0:
        if capture:
            print(red(f"  ✗ Error: {result.stderr.strip()}"))
        sys.exit(1)
    return result


# ── resolve paths ───────────────────────────────────────────────────────────
BASE_DIR  = os.path.dirname(os.path.abspath(__file__))
VENV_DIR  = os.path.join(BASE_DIR, "venv")
IS_WIN    = platform.system() == "Windows"
PY        = sys.executable
PIP       = os.path.join(VENV_DIR, "Scripts" if IS_WIN else "bin", "pip")
PYTHON    = os.path.join(VENV_DIR, "Scripts" if IS_WIN else "bin", "python")
ENV_FILE  = os.path.join(BASE_DIR, ".env")
ENV_EXMPL = os.path.join(BASE_DIR, ".env.example")


# ══════════════════════════════════════════════════════════════════════════════
# STEP 2 — Virtual environment
# ══════════════════════════════════════════════════════════════════════════════
step(2, "Creating Python virtual environment")

if os.path.exists(VENV_DIR):
    print(yellow("  ⚠  venv/ already exists — skipping creation."))
else:
    print(f"  Creating venv at {VENV_DIR} …")
    run(f'"{PY}" -m venv "{VENV_DIR}"')
    print(green("  ✔  Virtual environment created."))


# ══════════════════════════════════════════════════════════════════════════════
# STEP 3 — Install dependencies
# ══════════════════════════════════════════════════════════════════════════════
step(3, "Installing dependencies from requirements.txt")

req_file = os.path.join(BASE_DIR, "requirements.txt")
if not os.path.exists(req_file):
    print(red("  ✗  requirements.txt not found!"))
    sys.exit(1)

print("  Running pip install (this may take ~1 minute) …")
run(f'"{PIP}" install --upgrade pip -q')
run(f'"{PIP}" install -r "{req_file}" -q')
print(green("  ✔  All packages installed."))


# ══════════════════════════════════════════════════════════════════════════════
# STEP 4 — Set up .env file
# ══════════════════════════════════════════════════════════════════════════════
step(4, "Setting up .env configuration file")

if os.path.exists(ENV_FILE):
    print(yellow("  ⚠  .env already exists — skipping copy."))
else:
    shutil.copy(ENV_EXMPL, ENV_FILE)
    print(f"  Copied .env.example → .env")

print()
print(bold("  Please enter your configuration values."))
print(bold("  (Press ENTER to keep the default shown in brackets)"))
print()

def ask(prompt, default="", secret=False):
    display = f"[{default}]" if default else ""
    label = f"  {prompt} {display}: "
    if secret and default:
        label = f"  {prompt} [****]: "
    val = getpass.getpass(label) if secret else input(label)
    return val.strip() or default


db_host     = ask("MySQL host",            "localhost")
db_port     = ask("MySQL port",            "3306")
db_user     = ask("MySQL username",        "root")
db_password = ask("MySQL password",        secret=True)
db_name     = ask("Database name",         "industrial_safety_db")

twilio_sid  = ask("Twilio Account SID",    "")
twilio_tok  = ask("Twilio Auth Token",     "", secret=True)
twilio_from = ask("Twilio FROM number",    "+1XXXXXXXXXX")
alert_to    = ask("Alert TO number",       "+919322511660")

app_secret  = ask("App secret key",        "change_me_in_production_" + os.urandom(4).hex())
jwt_secret  = ask("JWT secret key",        "change_jwt_" + os.urandom(4).hex())

# Write .env
with open(ENV_FILE, "w") as f:
    f.write(f"""# Auto-generated by setup.py — DO NOT COMMIT THIS FILE

APP_ENV=development
APP_SECRET_KEY={app_secret}
APP_HOST=0.0.0.0
APP_PORT=8000
DEBUG=True

DB_HOST={db_host}
DB_PORT={db_port}
DB_USER={db_user}
DB_PASSWORD={db_password}
DB_NAME={db_name}

TWILIO_ACCOUNT_SID={twilio_sid}
TWILIO_AUTH_TOKEN={twilio_tok}
TWILIO_FROM_NUMBER={twilio_from}
ALERT_TO_NUMBER={alert_to}

ANOMALY_THRESHOLD=0.85
AI_MODEL_PATH=app/models/safety_model.pkl

JWT_SECRET_KEY={jwt_secret}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
""")
print(green("  ✔  .env file written successfully."))


# ══════════════════════════════════════════════════════════════════════════════
# STEP 5 — Create MySQL database & tables
# ══════════════════════════════════════════════════════════════════════════════
step(5, "Creating MySQL database and tables")

# Try to create the database
try:
    import pymysql
    conn = pymysql.connect(
        host=db_host,
        port=int(db_port),
        user=db_user,
        password=db_password,
    )
    with conn.cursor() as cur:
        cur.execute(
            f"CREATE DATABASE IF NOT EXISTS `{db_name}` "
            f"CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
        )
    conn.close()
    print(green(f"  ✔  Database '{db_name}' created (or already exists)."))
except Exception as exc:
    print(yellow(f"  ⚠  Could not create database automatically: {exc}"))
    print(yellow("     Please create it manually:"))
    print(yellow(f'     mysql -u {db_user} -p -e "CREATE DATABASE {db_name};"'))
    print(yellow("     Then re-run:  python run.py"))

# Create all tables via SQLAlchemy
print("  Creating all tables via SQLAlchemy …")
create_tables_script = f"""
import sys, os
sys.path.insert(0, r"{BASE_DIR}")
os.chdir(r"{BASE_DIR}")
from dotenv import load_dotenv
load_dotenv(r"{ENV_FILE}")
from app.core.database import Base, engine
import app.models.db_models
Base.metadata.create_all(bind=engine)
print("Tables created.")
"""
result = subprocess.run(
    [PYTHON, "-c", create_tables_script],
    capture_output=True, text=True
)
if result.returncode == 0:
    print(green("  ✔  All database tables created."))
else:
    print(yellow(f"  ⚠  Table creation skipped (DB not reachable): {result.stderr.strip()[:120]}"))
    print(yellow("     Tables will be auto-created when you run the app."))


# ══════════════════════════════════════════════════════════════════════════════
# Done!
# ══════════════════════════════════════════════════════════════════════════════
print()
print("═" * 50)
print(green(bold("  ✅ Setup complete!")))
print("═" * 50)
print()
print(bold("  To start the application, run:"))
print()
print(f"    {green('python run.py')}")
print()
print("  Or manually:")
if IS_WIN:
    print(f"    venv\\Scripts\\activate")
else:
    print(f"    source venv/bin/activate")
print(f"    uvicorn app.main:app --reload")
print()
print(f"  Dashboard → {bold('http://localhost:8000')}")
print(f"  API Docs  → {bold('http://localhost:8000/docs')}")
print()
